package me.drownek.util.localization;

public enum MessageKey {
    COMMAND_UTIL_SUCCESS_MESSAGE,
    COMMAND_UTIL_INVALID_ELEMENT,
    COMMAND_UTIL_ELEMENT_MISSING,
    COMMAND_UTIL_ELEMENT_ALREADY_EXIST,
    COMMAND_UTIL_LIST_EMPTY,
    COMMAND_UTIL_LIST_CONTENTS,
    COMMAND_UTIL_NO_SUCH_ELEMENT,

    CONFIRM_GUI_ARE_YOU_SURE,
    CONFIRM_GUI_YES,
    CONFIRM_GUI_NO,

    GUI_HELPER_BACK,
    GUI_HELPER_NEXT,
    GUI_HELPER_PREVIOUS,

    TEXT_UTIL_NOTHING,
    TEXT_UTIL_LOCATION_TELEPORT_FORMAT,

    TIME_UTIL_NEVER,

    WAITING_TASK_ALREADY_DOING_ACTION,
    WAITING_TASK_SNEAK_TO_CANCEL,

    AMOUNT_GUI_CANCEL,
}
